---
kind: pipeline
type: docker
name: build
steps:
    - name: submodules
      image: alpine/git
      environment:
        SSH_KEY:
          from_secret: ssh_key
      commands:
        - git submodule init
        - 'git config --global  url."https://github.com/".insteadOf git@github.com:'
        - 'git submodule update --recursive --remote'

    - name: clean
      image: alpine
      commands:
        - rm -rf /tmp/output/*
      volumes:
         - name: output
           path: /tmp/output

    - name: build
      image: ghcr.io/getzola/zola:v0.21.0
      entrypoint: [/bin/zola]
      command: ["build", "--output-dir", "/tmp/output/files/"]
      volumes:
        - name: output
          path: /tmp/output

volumes:
    - name: output
      host:
        path: /var/docker-volumes/linnenberg-dev/site
