---
kind: pipeline
type: docker
name: build
steps:
    - name: submodules
      image: alpine/git
      environment:
        SSH_KEY:
          from_secret: ssh_key
      commands:
        - git submodule init
        - 'git config --global  url."https://github.com/".insteadOf git@github.com:'
        - 'git submodule update --recursive --remote'

    - name: clean
      image: alpine
      commands:
        - rm -rf /tmp/output/*
      volumes:
         - name: output
           path: /tmp/output

    - name: build
      image: alpine
      command:
        - apk add make
        - make build-ci
      volumes:
        - name: output
          path: /tmp/output

volumes:
    - name: output
      host:
        path: /var/docker-volumes/linnenberg-dev/site
