---
kind: pipeline
type: docker
name: build
steps:

    - name: clean
      image: alpine
      commands:
        - rm -rf /tmp/output/*
      volumes:
         - name: output
           path: /tmp/output

    - name: build
      image: alpine
      commands:
        - apk add make curl
        - make build-ci
      volumes:
        - name: output
          path: /tmp/output

volumes:
    - name: output
      host:
        path: /var/docker-volumes/linnenberg-dev/site
